import type { AIAgent } from "@/types";

export const mockAgents: AIAgent[] = [
  {
    id: "agent-001",
    name: "Global Search Agent",
    purpose: "Identifies family offices and private capital groups from approved public sources and classifies them by geography, sector, and capital orientation.",
    input: "Search parameters: region, country, sector focus, prospect category, search depth",
    output: "Structured prospect list with basic profile fields and public source references",
    status: "Mock",
    lastRun: "2026-06-25T14:32:00Z",
    humanApprovalRequired: false,
    icon: "🔍",
  },
  {
    id: "agent-002",
    name: "Entity Classification Agent",
    purpose: "Classifies identified entities into the correct prospect category (SFO, MFO, holding company, HNWI entity, etc.) and validates the classification.",
    input: "Raw prospect name, public source URL, available profile data",
    output: "Confirmed prospect type, classification confidence score, alternative classifications",
    status: "Mock",
    lastRun: "2026-06-25T14:35:00Z",
    humanApprovalRequired: false,
    icon: "🏷️",
  },
  {
    id: "agent-003",
    name: "Source Verification Agent",
    purpose: "Verifies that all prospect data has been sourced from publicly available and ethically approved sources. Flags any potentially restricted or confidential data.",
    input: "Prospect profile with source URLs and data fields",
    output: "Source quality rating, verification status, flagged data fields, ethical source confirmation",
    status: "Mock",
    lastRun: "2026-06-25T14:37:00Z",
    humanApprovalRequired: true,
    icon: "🔒",
  },
  {
    id: "agent-004",
    name: "Prospect Profiling Agent",
    purpose: "Summarises each prospect's public background, identifies sector interests, detects long-horizon or permanent-capital indicators, and highlights governance themes.",
    input: "Prospect name, website, public source URLs, known sector interests",
    output: "Full prospect profile with investment philosophy, capital orientation, sector exposure, and TBP relevance summary",
    status: "Mock",
    lastRun: "2026-06-24T09:15:00Z",
    humanApprovalRequired: false,
    icon: "📋",
  },
  {
    id: "agent-005",
    name: "Suitability Scoring Agent",
    purpose: "Applies the TBP Founding Strategic Steward 100-point scoring model to each prospect, classifies them into priority tiers, and flags insufficient data.",
    input: "Complete prospect profile with all required data fields",
    output: "Suitability score (0–100), classification tier, 6-dimension scoring breakdown, confidence level, missing data flags",
    status: "Mock",
    lastRun: "2026-06-25T10:00:00Z",
    humanApprovalRequired: false,
    icon: "⭐",
  },
  {
    id: "agent-006",
    name: "Corridor Matching Agent",
    purpose: "Matches each prospect to the most relevant TBP corridor or opportunity area based on geography, sector exposure, and capital orientation.",
    input: "Scored prospect profile",
    output: "Primary corridor match, secondary corridor matches, relevance scores, suggested conversation angles",
    status: "Mock",
    lastRun: "2026-06-25T10:05:00Z",
    humanApprovalRequired: false,
    icon: "🗺️",
  },
  {
    id: "agent-007",
    name: "Briefing Pack Agent",
    purpose: "Generates internal briefing packs for selected prospects, including background notes, TBP relevance angles, draft emails, meeting agendas, and action templates.",
    input: "Prospect profile with scoring, corridor match, and approved conversation angle",
    output: "Full 11-section briefing pack for internal TBP use",
    status: "Mock",
    lastRun: "2026-06-25T11:30:00Z",
    humanApprovalRequired: true,
    icon: "📄",
  },
  {
    id: "agent-008",
    name: "Governance Language Agent",
    purpose: "Reviews all draft outreach materials for governance compliance, flags risky phrases, and suggests approved TBP language alternatives.",
    input: "Draft text (emails, briefing notes, deck copy)",
    output: "Risk score, flagged phrases with replacements, approval status (Safe / Needs Review / Blocked), recommended disclaimer",
    status: "Mock",
    lastRun: "2026-06-25T12:00:00Z",
    humanApprovalRequired: false,
    icon: "🛡️",
  },
  {
    id: "agent-009",
    name: "Diligence Risk Agent",
    purpose: "Analyses prospects for potential diligence risks including governance gaps, political sensitivity, data source quality, and engagement readiness challenges.",
    input: "Prospect profile, scoring breakdown, source verification status",
    output: "Diligence risk assessment, flagged risk areas, recommended additional research, engagement risk rating",
    status: "Needs API",
    humanApprovalRequired: true,
    icon: "⚠️",
  },
  {
    id: "agent-010",
    name: "Pipeline Tracking Agent",
    purpose: "Tracks all prospects through the 15-stage pipeline, monitors the 20 Founding Strategic Steward target, and alerts on stalled prospects or overdue actions.",
    input: "Current pipeline state, next action dates, assigned owners",
    output: "Pipeline status report, overdue action alerts, 20-steward target progress, stage transition recommendations",
    status: "Mock",
    lastRun: "2026-06-26T08:00:00Z",
    humanApprovalRequired: false,
    icon: "📊",
  },
  {
    id: "agent-011",
    name: "Data Room Agent",
    purpose: "Manages document tracking across all TBP materials, monitors approval status, links documents to prospects, and flags outdated versions.",
    input: "Document library state, version history, approval records",
    output: "Document status report, pending approval list, version alerts, external-approval-ready document list",
    status: "Mock",
    lastRun: "2026-06-26T08:05:00Z",
    humanApprovalRequired: false,
    icon: "🗂️",
  },
  {
    id: "agent-012",
    name: "Warm Introduction Agent",
    purpose: "Identifies potential warm introduction pathways for each prospect via shared networks, advisers, conferences, or known relationships.",
    input: "Prospect profile, known adviser relationships, network connections",
    output: "Ranked introduction pathways, key connector identification, recommended approach strategy",
    status: "Needs API",
    humanApprovalRequired: true,
    icon: "🤝",
  },
];
