import type { Document } from "@/types";

export const mockDocuments: Document[] = [
  {
    id: "doc-001",
    title: "TBP Protocol Establishment Round Deck",
    status: "Approved (Internal)",
    owner: "Ribi Jayasinghe",
    version: "v2.1",
    lastUpdated: "2026-06-20",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: [],
    notes: "Core deck for steward introduction. Requires TBP Leadership approval before external sharing.",
    category: "Core Documents",
  },
  {
    id: "doc-002",
    title: "TBP Founding Strategic Family Office Circle Brief",
    status: "Approved (Internal)",
    owner: "Ribi Jayasinghe",
    version: "v1.3",
    lastUpdated: "2026-06-18",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: ["p-005", "p-012", "p-018"],
    notes: "Key introductory document. Awaiting external approval from TBP Leadership and legal advisers.",
    category: "Core Documents",
  },
  {
    id: "doc-003",
    title: "Governance & Safeguard Language Note",
    status: "Approved (Internal)",
    owner: "Ribi Jayasinghe",
    version: "v1.0",
    lastUpdated: "2026-06-15",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: [],
    notes: "Internal compliance reference. Not for external distribution.",
    category: "Compliance",
  },
  {
    id: "doc-004",
    title: "New York/Newark Corridor Brief",
    status: "In Review",
    owner: "Global Strategist",
    version: "v0.3",
    lastUpdated: "2026-06-22",
    approvedInternal: false,
    approvedExternal: false,
    linkedProspects: ["p-001", "p-002"],
    notes: "Under review by TBP Capital Advisory Lead. Expected approval by end of June.",
    category: "Corridor Briefs",
  },
  {
    id: "doc-005",
    title: "London Canary Wharf Corridor Brief",
    status: "In Review",
    owner: "Global Strategist",
    version: "v0.4",
    lastUpdated: "2026-06-23",
    approvedInternal: false,
    approvedExternal: false,
    linkedProspects: ["p-003", "p-004", "p-028"],
    notes: "Draft in review. Requires legal input on UK regulatory framing.",
    category: "Corridor Briefs",
  },
  {
    id: "doc-006",
    title: "Indonesia Southeast Asia Corridor Brief",
    status: "Approved (Internal)",
    owner: "TBP Advisory",
    version: "v1.1",
    lastUpdated: "2026-06-25",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: ["p-005", "p-006", "p-007", "p-008"],
    notes: "Approved for internal briefing use. External version pending governance sign-off.",
    category: "Corridor Briefs",
  },
  {
    id: "doc-007",
    title: "Saudi Red Sea Corridor Brief",
    status: "Approved (Internal)",
    owner: "Global Strategist",
    version: "v1.0",
    lastUpdated: "2026-06-20",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: ["p-012", "p-013", "p-014", "p-027"],
    notes: "Ready for internal use. Priority brief given active Gulf pipeline.",
    category: "Corridor Briefs",
  },
  {
    id: "doc-008",
    title: "ASMOFP™ Offshore Energy / Data Infrastructure Note",
    status: "Draft",
    owner: "TBP Advisory",
    version: "v0.2",
    lastUpdated: "2026-06-18",
    approvedInternal: false,
    approvedExternal: false,
    linkedProspects: ["p-006", "p-014"],
    notes: "Early draft. Needs review from technical and governance teams before internal approval.",
    category: "Technical Notes",
  },
  {
    id: "doc-009",
    title: "Economic Impact Assumptions",
    status: "Draft",
    owner: "TBP Advisory",
    version: "v0.1",
    lastUpdated: "2026-06-10",
    approvedInternal: false,
    approvedExternal: false,
    linkedProspects: [],
    notes: "Working document only. Not for distribution.",
    category: "Research",
  },
  {
    id: "doc-010",
    title: "Singapore Family Office A — Briefing Pack",
    status: "Approved (Internal)",
    owner: "TBP Advisory",
    version: "v1.0",
    lastUpdated: "2026-06-25",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: ["p-005"],
    notes: "Briefing pack generated and reviewed. Awaiting TBP Leadership approval before approach.",
    category: "Prospect Briefing Packs",
  },
  {
    id: "doc-011",
    title: "Saudi Arabia Red Sea FO — Briefing Pack",
    status: "Approved (Internal)",
    owner: "Global Strategist",
    version: "v1.0",
    lastUpdated: "2026-06-24",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: ["p-012"],
    notes: "Approved for TBP Leadership review. External approach subject to Leadership sign-off.",
    category: "Prospect Briefing Packs",
  },
  {
    id: "doc-012",
    title: "Switzerland Stewardship Group — Briefing Pack",
    status: "Approved (Internal)",
    owner: "Global Strategist",
    version: "v1.0",
    lastUpdated: "2026-06-23",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: ["p-018"],
    notes: "Approved internally. Prospect in Reviewed stage — Leadership approval required before approach.",
    category: "Prospect Briefing Packs",
  },
  {
    id: "doc-013",
    title: "Follow-Up Email Template — Standard",
    status: "Approved (Internal)",
    owner: "Ribi Jayasinghe",
    version: "v1.2",
    lastUpdated: "2026-06-15",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: [],
    notes: "Standard template for post-introduction follow-up. All use must be checked through Language Guard before sending.",
    category: "Templates",
  },
  {
    id: "doc-014",
    title: "Meeting Agenda Template — Standard",
    status: "Approved (Internal)",
    owner: "Ribi Jayasinghe",
    version: "v1.0",
    lastUpdated: "2026-06-12",
    approvedInternal: true,
    approvedExternal: false,
    linkedProspects: [],
    notes: "Standard meeting agenda framework. Customise per prospect before use.",
    category: "Templates",
  },
];
