import type { Prospect } from "@/types";

export const mockProspects: Prospect[] = [
  // ── NEW YORK / NEW JERSEY ──────────────────────────────────
  {
    id: "p-001",
    prospect_name: "New York Private Capital Group A",
    prospect_type: "single-family-office",
    country: "United States",
    city: "New York",
    region: "North America",
    website: "https://example.com",
    public_source_url: "https://example.com/source",
    source_quality: "High",
    key_public_contacts: "Senior Family Principal (publicly known)",
    family_or_group_background:
      "Third-generation family office with roots in trade finance and port logistics. The founding family built wealth through container shipping and warehousing across the US East Coast. Now manages a diversified permanent-capital portfolio including real assets, infrastructure debt, and emerging market equities.",
    investment_philosophy:
      "Patient, multi-generational capital deployment with a focus on hard assets, infrastructure, and global trade infrastructure. Avoids short-term speculation; targets 10-20 year hold periods.",
    known_investment_themes: ["Trade finance", "Port logistics", "Infrastructure debt", "Emerging markets"],
    sector_interests: ["Trade", "Logistics", "Ports", "Infrastructure", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Strong alignment with TBP's New York/Newark North America Neutral Trade Corridor. Family's existing port and logistics infrastructure exposure maps directly onto TBP's trade corridor thesis. Long-duration capital orientation is a strong fit for the Protocol Establishment Round.",
    best_tbp_entry_point: "TBP New York/Newark North America Neutral Trade Corridor",
    suggested_conversation_angle:
      "Founding Stewardship Layer — positioning TBP's neutral trade protocol as a governance-safe, infrastructure-adjacent layer that complements their existing port and logistics portfolio.",
    recommended_contact_route: "Through established trade finance networks or port authority advisory channels",
    likely_diligence_questions: [
      "What is the governance structure of the Protocol Establishment Round?",
      "How does stewardship commitment relate to future project allocation?",
      "What is the timeline for corridor operationalisation?",
    ],
    diligence_flags: ["AUM not publicly confirmed", "Contact details require research"],
    suitability_score: 88,
    scoring_breakdown: {
      familyOfficeFit: 19,
      permanentCapitalOrientation: 20,
      sectorAlignment: 19,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 10,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Tharushi",
    next_action: "Generate briefing pack",
    next_action_date: "2026-07-10",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-20T00:00:00Z",
  },
  {
    id: "p-002",
    prospect_name: "New Jersey Infrastructure Family Office B",
    prospect_type: "family-holding-company",
    country: "United States",
    city: "Newark",
    region: "North America",
    source_quality: "Medium",
    key_public_contacts: "Founding principal — named in infrastructure conference proceedings",
    family_or_group_background:
      "Family holding company with significant exposure to energy infrastructure and industrial real estate across the US Northeast. The group has participated in multiple public-private partnership structures.",
    investment_philosophy:
      "Institutional-grade infrastructure and energy transition investments. Long hold periods, co-investment preferred, strong governance emphasis.",
    known_investment_themes: ["Energy infrastructure", "Industrial real estate", "Public-private partnerships"],
    sector_interests: ["Energy", "Infrastructure", "Real Estate"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "High",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "Low",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Relevant for TBP's New York/Newark Corridor and ASMOFP™ Offshore Energy angle. Energy infrastructure exposure is a strong secondary hook.",
    best_tbp_entry_point: "TBP New York/Newark North America Neutral Trade Corridor",
    suggested_conversation_angle:
      "Strategic adjacency — energy and infrastructure transition aligned with TBP's neutral corridor formation layer.",
    recommended_contact_route: "Infrastructure conference networks, public-private partnership forums",
    likely_diligence_questions: ["What regulatory jurisdiction governs the Protocol?", "Is this a regulated financial product?"],
    diligence_flags: ["Low emerging market exposure — corridor relevance may need tailoring"],
    suitability_score: 74,
    scoring_breakdown: {
      familyOfficeFit: 17,
      permanentCapitalOrientation: 18,
      sectorAlignment: 16,
      governanceInstitutionalMindset: 10,
      strategicAdjacencyTBP: 8,
      engagementReadiness: 5,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Profiled",
    assigned_owner: "Tharushi",
    next_action: "Score prospect and prepare corridor matching note",
    next_action_date: "2026-07-15",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-05T00:00:00Z",
    updated_at: "2026-06-21T00:00:00Z",
  },

  // ── LONDON / UK ──────────────────────────────────────────
  {
    id: "p-003",
    prospect_name: "London Family Capital Group C",
    prospect_type: "multi-family-office",
    country: "United Kingdom",
    city: "London",
    region: "United Kingdom & Europe",
    source_quality: "High",
    key_public_contacts: "Managing Director publicly named in Campden Wealth reports",
    family_or_group_background:
      "Multi-family office based in Mayfair, London, managing capital for several European entrepreneurial families. Significant exposure to trade and logistics, maritime, and cross-border infrastructure. Known for long-duration co-investment approach.",
    investment_philosophy:
      "Stewardship-oriented permanent capital with a focus on real assets, trade infrastructure, and digital logistics networks across Europe and emerging corridors.",
    known_investment_themes: ["Maritime infrastructure", "Cross-border logistics", "Digital trade networks", "Emerging corridor infrastructure"],
    sector_interests: ["Trade", "Logistics", "Maritime", "Ports", "Data Infrastructure"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "High",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Excellent fit with TBP London Canary Wharf Neutral Trade City / Corridor and TBP Global Nomadic Trader Ecosystem. Strong alignment on maritime, trade protocol and digital infrastructure themes.",
    best_tbp_entry_point: "TBP London Canary Wharf Neutral Trade City / Corridor",
    suggested_conversation_angle:
      "Institutional formation round — positioning TBP's London corridor as a governance-layer for cross-border neutral trade infrastructure that complements their existing maritime and logistics exposure.",
    recommended_contact_route: "Campden Wealth network, family office forums (e.g., SuperReturn, FO Forum London)",
    likely_diligence_questions: [
      "How is the London corridor structured legally?",
      "What is the relationship between stewardship commitment and future project access?",
    ],
    diligence_flags: [],
    suitability_score: 91,
    scoring_breakdown: {
      familyOfficeFit: 19,
      permanentCapitalOrientation: 20,
      sectorAlignment: 20,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 12,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack and seek warm introduction via FO Forum",
    next_action_date: "2026-07-08",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-02T00:00:00Z",
    updated_at: "2026-06-22T00:00:00Z",
  },
  {
    id: "p-004",
    prospect_name: "UK Permanent Capital Stewardship Group D",
    prospect_type: "permanent-capital-private-group",
    country: "United Kingdom",
    city: "London",
    region: "United Kingdom & Europe",
    source_quality: "Medium",
    key_public_contacts: "Chairman named in trade association publications",
    family_or_group_background:
      "Permanent-capital private group with roots in UK industrial manufacturing and energy transition. Known for generational stewardship philosophy and long-duration infrastructure holds.",
    investment_philosophy:
      "Generational stewardship of industrial and energy assets. Patient capital with 15+ year hold periods. Active in public-private infrastructure formation.",
    known_investment_themes: ["Energy transition", "Industrial platforms", "Infrastructure formation"],
    sector_interests: ["Energy", "Infrastructure", "Manufacturing", "Industrial Platforms"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "Low",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "Low",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Strong fit for TBP's ASMOFP™ Offshore Energy / Data Infrastructure angle and the Protocol Establishment Round governance layer.",
    best_tbp_entry_point: "ASMOFP™ Offshore Energy / Data Infrastructure",
    suggested_conversation_angle:
      "Governance dialogue — framing TBP's protocol as a neutral stewardship layer for offshore energy and data infrastructure with long-duration institutional formation alignment.",
    recommended_contact_route: "Energy industry associations, infrastructure co-investment forums",
    likely_diligence_questions: ["What governance body oversees TBP corridor development?"],
    diligence_flags: ["Limited emerging market exposure — frame conversation around domestic infrastructure first"],
    suitability_score: 78,
    scoring_breakdown: {
      familyOfficeFit: 17,
      permanentCapitalOrientation: 19,
      sectorAlignment: 17,
      governanceInstitutionalMindset: 12,
      strategicAdjacencyTBP: 8,
      engagementReadiness: 5,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Profiled",
    assigned_owner: "Global Strategist",
    next_action: "Score and generate corridor matching note",
    next_action_date: "2026-07-20",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-03T00:00:00Z",
    updated_at: "2026-06-23T00:00:00Z",
  },

  // ── SINGAPORE ─────────────────────────────────────────────
  {
    id: "p-005",
    prospect_name: "Singapore Family Office A",
    prospect_type: "single-family-office",
    country: "Singapore",
    city: "Singapore",
    region: "Southeast Asia",
    source_quality: "High",
    key_public_contacts: "Founder publicly named at FII Institute events",
    family_or_group_background:
      "Singapore-based single-family office established by a first-generation entrepreneur who built wealth in maritime logistics and port operations across Southeast Asia. Strong institutional governance framework. Actively exploring long-duration infrastructure and neutral trade corridor opportunities.",
    investment_philosophy:
      "Patient, governance-disciplined capital focused on trade infrastructure, maritime assets, and Southeast Asian corridor development. Strong institutional mindset with family governance council.",
    known_investment_themes: ["Maritime logistics", "Port infrastructure", "Southeast Asia corridors", "Neutral trade zones"],
    sector_interests: ["Trade", "Logistics", "Ports", "Maritime", "Infrastructure"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Exceptional fit with TBP Indonesia Southeast Asia Neutral Trade Corridor and TBP Global Nomadic Trader Ecosystem. Direct sector alignment with maritime and port infrastructure. Singapore base provides ideal gateway access.",
    best_tbp_entry_point: "TBP Indonesia Southeast Asia Neutral Trade Corridor",
    suggested_conversation_angle:
      "Founding Stewardship Layer — positioning TBP's Southeast Asia corridor as a natural extension of their existing maritime and port infrastructure thesis.",
    recommended_contact_route: "Singapore FO Association, FII Institute networks, port authority advisory channels",
    likely_diligence_questions: [
      "How does TBP's corridor relate to existing ASEAN trade frameworks?",
      "What is the stewardship commitment structure?",
    ],
    diligence_flags: [],
    suitability_score: 93,
    scoring_breakdown: {
      familyOfficeFit: 20,
      permanentCapitalOrientation: 20,
      sectorAlignment: 20,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 13,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Tharushi",
    next_action: "Generate briefing pack — highest priority",
    next_action_date: "2026-07-05",
    briefing_pack_status: "Generated",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-25T00:00:00Z",
  },
  {
    id: "p-006",
    prospect_name: "Singapore Strategic Holdings Group B",
    prospect_type: "family-controlled-investment-company",
    country: "Singapore",
    city: "Singapore",
    region: "Southeast Asia",
    source_quality: "High",
    key_public_contacts: "Executive Director named in Singapore Business Times",
    family_or_group_background:
      "Singapore-based family-controlled investment company with diversified exposure to real estate, data infrastructure, and Southeast Asian trade networks. The founding family has deep government and regulatory relationships in Singapore and the wider ASEAN region.",
    investment_philosophy:
      "Long-horizon capital with emphasis on digital infrastructure, real assets, and institutional co-investment. Known for governance discipline and regulatory alignment.",
    known_investment_themes: ["Digital infrastructure", "Real assets", "ASEAN trade", "Data centres"],
    sector_interests: ["Data Infrastructure", "Real Estate", "Technology", "Trade", "Infrastructure"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Low",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "High",
    technology_digital_infrastructure_exposure: "High",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Strong fit for TBP's ASMOFP™ Offshore Energy / Data Infrastructure and Indonesia corridor. Digital infrastructure and data centre exposure creates strong TBP adjacency.",
    best_tbp_entry_point: "ASMOFP™ Offshore Energy / Data Infrastructure",
    suggested_conversation_angle:
      "Strategic adjacency — aligning TBP's data and digital infrastructure corridor layer with their existing ASEAN data centre and digital logistics portfolio.",
    recommended_contact_route: "Singapore VC / FO peer networks, ASEAN digital infrastructure forums",
    likely_diligence_questions: ["How is the data infrastructure component governed?", "What co-investment rights exist for stewards?"],
    diligence_flags: [],
    suitability_score: 86,
    scoring_breakdown: {
      familyOfficeFit: 18,
      permanentCapitalOrientation: 19,
      sectorAlignment: 18,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 11,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Tharushi",
    next_action: "Generate briefing pack",
    next_action_date: "2026-07-10",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-02T00:00:00Z",
    updated_at: "2026-06-24T00:00:00Z",
  },

  // ── INDONESIA ─────────────────────────────────────────────
  {
    id: "p-007",
    prospect_name: "Indonesia Strategic Holding Group A",
    prospect_type: "family-holding-company",
    country: "Indonesia",
    city: "Jakarta",
    region: "Southeast Asia",
    source_quality: "High",
    key_public_contacts: "Family principal publicly named in Forbes Indonesia",
    family_or_group_background:
      "Jakarta-based family holding company with diversified exposure to logistics, energy, and digital infrastructure. The founding family has built significant wealth through port operations and energy distribution across the Indonesian archipelago.",
    investment_philosophy:
      "Generational capital with emphasis on logistics infrastructure, energy, and digital networks across Indonesia and Southeast Asia. Long-horizon holds, strong governance.",
    known_investment_themes: ["Port logistics", "Energy distribution", "Digital networks", "Infrastructure"],
    sector_interests: ["Logistics", "Energy", "Ports", "Infrastructure", "Data Infrastructure"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Priority prospect for TBP Indonesia Southeast Asia Neutral Trade Corridor. Direct sector alignment across logistics, energy and digital. Indonesia base is core to TBP's Southeast Asia corridor strategy.",
    best_tbp_entry_point: "TBP Indonesia Southeast Asia Neutral Trade Corridor",
    suggested_conversation_angle:
      "Institutional formation round — positioning TBP's Indonesia corridor as a governance-safe, neutral infrastructure layer for their existing logistics and energy portfolio.",
    recommended_contact_route: "Jakarta institutional banking channels, Indonesian Chamber of Commerce networks",
    likely_diligence_questions: ["What is TBP's relationship with Indonesian regulatory authorities?", "What is the stewardship commitment quantum?"],
    diligence_flags: ["Governance language not yet evident in public materials — verify internally"],
    suitability_score: 89,
    scoring_breakdown: {
      familyOfficeFit: 18,
      permanentCapitalOrientation: 19,
      sectorAlignment: 20,
      governanceInstitutionalMindset: 13,
      strategicAdjacencyTBP: 13,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Tharushi",
    next_action: "Generate briefing pack and research warm introduction path",
    next_action_date: "2026-07-07",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-25T00:00:00Z",
  },
  {
    id: "p-008",
    prospect_name: "Indonesia Private Capital Group B",
    prospect_type: "private-investment-group",
    country: "Indonesia",
    city: "Surabaya",
    region: "Southeast Asia",
    source_quality: "Medium",
    key_public_contacts: "Managing Director named in regional trade publications",
    family_or_group_background:
      "Surabaya-based private investment group with exposure to agribusiness, food logistics, and maritime trade across Eastern Indonesia. Strong regional relationships with local government bodies.",
    investment_philosophy:
      "Patient capital focused on food security infrastructure, logistics networks, and maritime trade routes in Eastern Indonesia and the wider region.",
    known_investment_themes: ["Agribusiness", "Food logistics", "Maritime trade", "Eastern Indonesia"],
    sector_interests: ["Food / Agribusiness", "Logistics", "Maritime", "Trade"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: false,
    direct_investment_activity: true,
    infrastructure_exposure: "Medium",
    energy_exposure: "Low",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Secondary fit for Indonesia corridor, particularly for food and agribusiness corridor themes within TBP's Global Nomadic Trader Ecosystem.",
    best_tbp_entry_point: "TBP Indonesia Southeast Asia Neutral Trade Corridor",
    suggested_conversation_angle:
      "Long-duration infrastructure formation — linking TBP's food corridor and maritime trade protocol to their existing agribusiness and maritime exposure.",
    recommended_contact_route: "Regional trade associations, agribusiness industry networks",
    likely_diligence_questions: ["How does TBP's corridor address food security?"],
    diligence_flags: ["Permanent capital indicators uncertain", "Limited governance language in public materials"],
    suitability_score: 67,
    scoring_breakdown: {
      familyOfficeFit: 15,
      permanentCapitalOrientation: 13,
      sectorAlignment: 15,
      governanceInstitutionalMindset: 10,
      strategicAdjacencyTBP: 9,
      engagementReadiness: 5,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Profiled",
    assigned_owner: "Tharushi",
    next_action: "Monitor and revisit in Q3",
    next_action_date: "2026-09-01",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-05T00:00:00Z",
    updated_at: "2026-06-20T00:00:00Z",
  },

  // ── SRI LANKA ─────────────────────────────────────────────
  {
    id: "p-009",
    prospect_name: "Sri Lanka Family Investment Group A",
    prospect_type: "family-controlled-investment-company",
    country: "Sri Lanka",
    city: "Colombo",
    region: "South Asia",
    source_quality: "Medium",
    key_public_contacts: "Chairman publicly named in LBO and Colombo Stock Exchange filings",
    family_or_group_background:
      "Colombo-based family-controlled investment company with diversified exposure to port infrastructure, real estate, and financial services. The founding family has generational ties to Sri Lanka's port economy and trade history.",
    investment_philosophy:
      "Long-horizon family stewardship with emphasis on infrastructure, real estate, and trade connectivity. Strong cultural alignment with generational permanence.",
    known_investment_themes: ["Port infrastructure", "Real estate", "Financial services", "Trade connectivity"],
    sector_interests: ["Ports", "Real Estate", "Financial Services", "Trade", "Infrastructure"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Low",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "High",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Relevant for TBP's Global Nomadic Trader Ecosystem and broader South Asia corridor interest. Port infrastructure exposure and generational stewardship orientation are strong alignment signals.",
    best_tbp_entry_point: "TBP Capital Advisory & Coordination Office",
    suggested_conversation_angle:
      "Governance dialogue — introducing TBP's institutional formation round as a complement to their existing port and trade infrastructure stewardship.",
    recommended_contact_route: "Colombo Stock Exchange networks, SLASSCOM, trade chamber connections",
    likely_diligence_questions: ["What is TBP's relationship with the Sri Lankan port authority?"],
    diligence_flags: ["Limited governance language publicly evident", "Emerging market risk sensitivity may apply"],
    suitability_score: 72,
    scoring_breakdown: {
      familyOfficeFit: 16,
      permanentCapitalOrientation: 17,
      sectorAlignment: 15,
      governanceInstitutionalMindset: 11,
      strategicAdjacencyTBP: 8,
      engagementReadiness: 5,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Profiled",
    assigned_owner: "Tharushi",
    next_action: "Develop corridor matching note and brief Ribi Jayasinghe",
    next_action_date: "2026-07-25",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-04T00:00:00Z",
    updated_at: "2026-06-22T00:00:00Z",
  },

  // ── CENTRAL ASIA ──────────────────────────────────────────
  {
    id: "p-010",
    prospect_name: "Central Asia Industrial Family Office A",
    prospect_type: "single-family-office",
    country: "Kazakhstan",
    city: "Almaty",
    region: "Central Asia",
    source_quality: "Medium",
    key_public_contacts: "Principal named in Kazakh Invest and AIFC publications",
    family_or_group_background:
      "Almaty-based single-family office managing multigenerational wealth built through energy, mining, and industrial manufacturing in Kazakhstan and the wider Central Asian region. The family has invested in trade corridors connecting Central Asia with China and Europe.",
    investment_philosophy:
      "Long-horizon industrial and energy capital with growing interest in corridor infrastructure and neutral trade zone development. Governance-aware with formal family constitution.",
    known_investment_themes: ["Energy", "Mining", "Industrial manufacturing", "Central Asia corridor", "China-Europe trade"],
    sector_interests: ["Energy", "Infrastructure", "Trade", "Logistics", "Industrial Platforms", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Excellent candidate for TBP's Global Nomadic Trader Ecosystem and TBP Neutral Trade Cities concept. Central Asian corridor exposure and energy infrastructure alignment create strong TBP adjacency.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Permanent-capital alignment — positioning TBP's neutral trade city concept as an institutional formation layer for Central Asian corridor infrastructure that bridges their existing energy and trade exposure.",
    recommended_contact_route: "AIFC (Astana International Financial Centre) networks, Kazakh Invest channels, EBRD connections",
    likely_diligence_questions: ["How does TBP's corridor interact with existing BRI infrastructure?", "What legal jurisdiction governs the formation round?"],
    diligence_flags: ["Geopolitical sensitivity — corridor positioning requires careful framing"],
    suitability_score: 85,
    scoring_breakdown: {
      familyOfficeFit: 18,
      permanentCapitalOrientation: 18,
      sectorAlignment: 19,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 10,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack with Central Asia corridor framing",
    next_action_date: "2026-07-12",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-03T00:00:00Z",
    updated_at: "2026-06-24T00:00:00Z",
  },
  {
    id: "p-011",
    prospect_name: "Uzbekistan Trade Capital Group B",
    prospect_type: "strategic-private-capital-group",
    country: "Uzbekistan",
    city: "Tashkent",
    region: "Central Asia",
    source_quality: "Low",
    key_public_contacts: "Unknown — research required",
    family_or_group_background:
      "Tashkent-based strategic private capital group with roots in cotton, logistics, and more recently digital infrastructure. The group has been expanding its exposure to international trade corridors.",
    investment_philosophy:
      "Emerging institutional capital with a focus on trade, logistics, and digital connectivity. Still developing formal governance structures.",
    known_investment_themes: ["Cotton trade", "Logistics", "Digital connectivity"],
    sector_interests: ["Trade", "Logistics", "Technology", "Emerging Markets"],
    long_horizon_capital_indicators: false,
    permanent_capital_indicators: false,
    direct_investment_activity: true,
    infrastructure_exposure: "Low",
    energy_exposure: "Medium",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Monitor prospect. Digital and logistics interest is relevant but governance and stewardship frameworks are still developing. May become more suitable as institutional maturity increases.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Introduce TBP's institutional formation framework as a governance and coordination layer for their developing corridor ambitions.",
    recommended_contact_route: "Tashkent trade networks, Uzbekistan government investment promotion bodies",
    likely_diligence_questions: ["What governance framework does the group operate under?"],
    diligence_flags: ["Low governance maturity", "Permanent capital indicators not yet evident", "Contact details require research"],
    suitability_score: 52,
    scoring_breakdown: {
      familyOfficeFit: 11,
      permanentCapitalOrientation: 9,
      sectorAlignment: 13,
      governanceInstitutionalMindset: 8,
      strategicAdjacencyTBP: 7,
      engagementReadiness: 4,
    },
    classification: "Monitor / Secondary Prospect",
    pipeline_stage: "Identified",
    assigned_owner: "Global Strategist",
    next_action: "Monitor and revisit in 6 months",
    next_action_date: "2026-12-01",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-10T00:00:00Z",
    updated_at: "2026-06-20T00:00:00Z",
  },

  // ── GULF ──────────────────────────────────────────────────
  {
    id: "p-012",
    prospect_name: "Saudi Arabia Red Sea Investment Family Office",
    prospect_type: "single-family-office",
    country: "Saudi Arabia",
    city: "Jeddah",
    region: "Gulf & Middle East",
    source_quality: "High",
    key_public_contacts: "Principal publicly named at FII Institute events",
    family_or_group_background:
      "Jeddah-based single-family office aligned with the Saudi Vision 2030 agenda. The family has significant exposure to Red Sea port infrastructure, energy, and logistics. Known for long-duration institutional capital deployment and governance discipline.",
    investment_philosophy:
      "Stewardship-oriented permanent capital aligned with Saudi Vision 2030. Focus on infrastructure, energy transition, and Red Sea corridor development. Institutional governance emphasis.",
    known_investment_themes: ["Red Sea corridor", "Energy transition", "Port infrastructure", "Vision 2030 alignment"],
    sector_interests: ["Ports", "Energy", "Infrastructure", "Trade", "Logistics"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Exceptional fit with TBP Saudi Red Sea Corridor and TBP Neutral Trade Cities. Direct alignment with Red Sea port and corridor infrastructure. FII Institute network provides credible warm introduction pathway.",
    best_tbp_entry_point: "TBP Saudi Red Sea Corridor",
    suggested_conversation_angle:
      "Founding Stewardship Layer — positioning TBP's Saudi Red Sea Corridor as an institutional formation layer that complements their existing Red Sea infrastructure and Vision 2030 alignment.",
    recommended_contact_route: "FII Institute network, Saudi investment conferences, Jeddah Chamber of Commerce",
    likely_diligence_questions: [
      "How does TBP's corridor align with NEOM and the Vision 2030 agenda?",
      "What is the governance relationship with Saudi regulatory authorities?",
    ],
    diligence_flags: [],
    suitability_score: 94,
    scoring_breakdown: {
      familyOfficeFit: 20,
      permanentCapitalOrientation: 20,
      sectorAlignment: 20,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 13,
      engagementReadiness: 7,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Approved for Approach",
    assigned_owner: "Global Strategist",
    next_action: "Seek warm introduction via FII Institute channel",
    next_action_date: "2026-07-05",
    briefing_pack_status: "Generated",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-26T00:00:00Z",
  },
  {
    id: "p-013",
    prospect_name: "Dubai Family Holding Group A",
    prospect_type: "family-holding-company",
    country: "UAE",
    city: "Dubai",
    region: "Gulf & Middle East",
    source_quality: "High",
    key_public_contacts: "CEO publicly named in Gulf Business and Arabian Business",
    family_or_group_background:
      "Dubai-based family holding company with diversified exposure to trade, real estate, financial services, and digital infrastructure. Long-established family with deep relationships across the GCC, South Asia and Africa.",
    investment_philosophy:
      "Diversified permanent-capital management across trade, real estate, and digital infrastructure. Strong cross-corridor orientation with GCC, South Asia, and African exposure.",
    known_investment_themes: ["GCC trade", "Real estate", "Digital infrastructure", "Africa connectivity"],
    sector_interests: ["Trade", "Real Estate", "Data Infrastructure", "Financial Services", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "Medium",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "High",
    technology_digital_infrastructure_exposure: "High",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Strong multi-corridor fit. Relevant for TBP Capital Advisory & Coordination Office, TBP Saudi Red Sea Corridor, and TBP Global Nomadic Trader Ecosystem. Cross-corridor relationships across GCC, South Asia, and Africa create exceptional strategic adjacency.",
    best_tbp_entry_point: "TBP Capital Advisory & Coordination Office",
    suggested_conversation_angle:
      "Strategic adjacency — introducing TBP as the coordination layer for their existing multi-corridor trade and infrastructure positions across GCC, South Asia, and Africa.",
    recommended_contact_route: "Dubai Chamber, Gulf Business networks, GCC family office peer networks",
    likely_diligence_questions: ["What is the TBP coordination role across corridors?", "How are stewards consulted on corridor development?"],
    diligence_flags: [],
    suitability_score: 87,
    scoring_breakdown: {
      familyOfficeFit: 18,
      permanentCapitalOrientation: 18,
      sectorAlignment: 18,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 12,
      engagementReadiness: 7,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack with multi-corridor framing",
    next_action_date: "2026-07-08",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-02T00:00:00Z",
    updated_at: "2026-06-25T00:00:00Z",
  },
  {
    id: "p-014",
    prospect_name: "Abu Dhabi Strategic Capital Group B",
    prospect_type: "permanent-capital-private-group",
    country: "UAE",
    city: "Abu Dhabi",
    region: "Gulf & Middle East",
    source_quality: "High",
    key_public_contacts: "Managing Director named at Abu Dhabi Investment Forum",
    family_or_group_background:
      "Abu Dhabi-based permanent capital group with significant exposure to energy infrastructure, port operations, and global logistics. The group operates with sovereign-adjacent discipline and long-duration capital mandates.",
    investment_philosophy:
      "Sovereign-adjacent permanent capital with 20+ year hold periods. Focus on energy, port and maritime infrastructure, and emerging corridor development.",
    known_investment_themes: ["Energy infrastructure", "Port and maritime", "Emerging corridor development", "Sovereign-adjacent capital"],
    sector_interests: ["Energy", "Ports", "Maritime", "Infrastructure", "Logistics", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Top-tier fit for TBP Saudi Red Sea Corridor, ASMOFP™ Offshore Energy / Data Infrastructure, and TBP Corridor Trust Bank concept. Sovereign-adjacent discipline and energy/port alignment create exceptional strategic adjacency.",
    best_tbp_entry_point: "ASMOFP™ Offshore Energy / Data Infrastructure",
    suggested_conversation_angle:
      "Permanent-capital alignment — positioning TBP as the governance and coordination layer for long-duration corridor and offshore energy infrastructure that aligns with their sovereign-grade capital mandate.",
    recommended_contact_route: "Abu Dhabi Investment Forum, ADGM networks, sovereign fund adjacent relationships",
    likely_diligence_questions: ["What is the TBP governance council structure?", "How does stewardship interact with project-level governance?"],
    diligence_flags: [],
    suitability_score: 92,
    scoring_breakdown: {
      familyOfficeFit: 19,
      permanentCapitalOrientation: 20,
      sectorAlignment: 20,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 13,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack with offshore energy framing",
    next_action_date: "2026-07-06",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-25T00:00:00Z",
  },
  {
    id: "p-015",
    prospect_name: "Qatar Family Office Group C",
    prospect_type: "single-family-office",
    country: "Qatar",
    city: "Doha",
    region: "Gulf & Middle East",
    source_quality: "Medium",
    key_public_contacts: "Family principal named in Qatar Financial Centre publications",
    family_or_group_background:
      "Doha-based single-family office with exposure to energy, real estate, and financial services. The family has Qatar Financial Centre relationships and a growing interest in global trade infrastructure.",
    investment_philosophy:
      "Multi-generational stewardship capital focused on real assets and energy infrastructure. Increasing international diversification towards neutral trade and corridor investment.",
    known_investment_themes: ["Energy", "Real estate", "Financial services", "International diversification"],
    sector_interests: ["Energy", "Real Estate", "Financial Services", "Trade"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: false,
    infrastructure_exposure: "Medium",
    energy_exposure: "High",
    logistics_transport_exposure: "Low",
    real_estate_exposure: "High",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "Medium",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Relevant secondary prospect for Gulf corridor and ASMOFP™ energy angle. Strong energy and real estate exposure but limited direct investment activity and low logistics alignment.",
    best_tbp_entry_point: "ASMOFP™ Offshore Energy / Data Infrastructure",
    suggested_conversation_angle:
      "Strategic adjacency — introducing TBP's offshore energy and corridor infrastructure layer as a governance-safe international diversification opportunity.",
    recommended_contact_route: "Qatar Financial Centre networks, QFC Advisory Board channels",
    likely_diligence_questions: ["Is TBP registered or regulated in Qatar?"],
    diligence_flags: ["Direct investment activity not yet confirmed publicly", "Governance language absent from public materials"],
    suitability_score: 69,
    scoring_breakdown: {
      familyOfficeFit: 17,
      permanentCapitalOrientation: 16,
      sectorAlignment: 14,
      governanceInstitutionalMindset: 10,
      strategicAdjacencyTBP: 8,
      engagementReadiness: 4,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Profiled",
    assigned_owner: "Global Strategist",
    next_action: "Score and prepare corridor matching note",
    next_action_date: "2026-07-30",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-06T00:00:00Z",
    updated_at: "2026-06-22T00:00:00Z",
  },

  // ── JOHANNESBURG / SOUTH AFRICA ───────────────────────────
  {
    id: "p-016",
    prospect_name: "Johannesburg Private Capital Group A",
    prospect_type: "family-controlled-investment-company",
    country: "South Africa",
    city: "Johannesburg",
    region: "Africa",
    source_quality: "High",
    key_public_contacts: "Founding principal named in Business Day and JSE filings",
    family_or_group_background:
      "Johannesburg-based family-controlled investment company with significant exposure to mining infrastructure, logistics, and African corridor development. The founding family has built multigenerational wealth through South African mining and industrial logistics.",
    investment_philosophy:
      "Generational stewardship capital with a focus on hard assets, mining infrastructure, logistics corridors, and emerging African market development.",
    known_investment_themes: ["Mining infrastructure", "African logistics corridors", "Emerging markets", "Industrial platforms"],
    sector_interests: ["Infrastructure", "Logistics", "Emerging Markets", "Industrial Platforms", "Trade"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Strong fit for TBP Global Nomadic Trader Ecosystem and TBP Neutral Trade Cities. African corridor and logistics exposure creates strategic adjacency for TBP's emerging markets and corridor strategy.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Long-duration infrastructure formation — positioning TBP's neutral trade city and corridor concept as a governance layer for their existing African logistics and mining infrastructure portfolio.",
    recommended_contact_route: "JSE investor relations networks, South African Chamber of Business, African Development Bank circles",
    likely_diligence_questions: ["What is TBP's engagement with African regulatory bodies?"],
    diligence_flags: ["Governance stewardship language not yet publicly evident"],
    suitability_score: 80,
    scoring_breakdown: {
      familyOfficeFit: 17,
      permanentCapitalOrientation: 18,
      sectorAlignment: 18,
      governanceInstitutionalMindset: 12,
      strategicAdjacencyTBP: 10,
      engagementReadiness: 5,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack with Africa corridor framing",
    next_action_date: "2026-07-15",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-04T00:00:00Z",
    updated_at: "2026-06-24T00:00:00Z",
  },

  // ── LUXEMBOURG ────────────────────────────────────────────
  {
    id: "p-017",
    prospect_name: "Luxembourg Multi-Family Office Group A",
    prospect_type: "multi-family-office",
    country: "Luxembourg",
    city: "Luxembourg City",
    region: "United Kingdom & Europe",
    source_quality: "High",
    key_public_contacts: "Managing Partner named in Private Wealth magazine and Luxembourg FO Association",
    family_or_group_background:
      "Luxembourg-based multi-family office managing European and global family capital across infrastructure, trade, and private equity. Known for institutional governance standards and long-duration capital mandates.",
    investment_philosophy:
      "Institutional-grade permanent capital management with deep infrastructure, private equity, and trade finance exposure. 10-25 year hold periods standard.",
    known_investment_themes: ["Infrastructure", "Private equity", "Trade finance", "European corridor", "Global diversification"],
    sector_interests: ["Infrastructure", "Trade", "Financial Services", "Energy", "Real Estate"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "High",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Strong fit for TBP London Canary Wharf Corridor and TBP Capital Advisory & Coordination Office. Institutional governance standards and multi-corridor exposure create strong adjacency.",
    best_tbp_entry_point: "TBP Capital Advisory & Coordination Office",
    suggested_conversation_angle:
      "Institutional formation round — positioning TBP's Capital Advisory structure as a governance-safe co-ordination layer for their existing global multi-corridor infrastructure exposure.",
    recommended_contact_route: "Luxembourg Private Equity & Venture Capital Association (LPEA), Alfi networks",
    likely_diligence_questions: ["What Luxembourg legal structures are compatible with the Protocol Establishment Round?"],
    diligence_flags: [],
    suitability_score: 83,
    scoring_breakdown: {
      familyOfficeFit: 18,
      permanentCapitalOrientation: 19,
      sectorAlignment: 17,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 9,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack",
    next_action_date: "2026-07-14",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-03T00:00:00Z",
    updated_at: "2026-06-24T00:00:00Z",
  },

  // ── SWITZERLAND ───────────────────────────────────────────
  {
    id: "p-018",
    prospect_name: "Switzerland Private Capital Stewardship Group A",
    prospect_type: "permanent-capital-private-group",
    country: "Switzerland",
    city: "Geneva",
    region: "United Kingdom & Europe",
    source_quality: "High",
    key_public_contacts: "Partner named in Campden Wealth and Swiss Family Office journal",
    family_or_group_background:
      "Geneva-based permanent capital group managing multi-generational family wealth across infrastructure, trade, and financial services. Known for exceptionally rigorous governance standards and a stewardship-first investment philosophy.",
    investment_philosophy:
      "Governance-first permanent capital. Infrastructure, trade and financial services with 20+ year mandates. Actively seeking institutional co-formation opportunities with strong governance safeguards.",
    known_investment_themes: ["Infrastructure co-formation", "Trade infrastructure", "Financial services", "Governance-first investment"],
    sector_interests: ["Infrastructure", "Trade", "Financial Services", "Energy"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "Medium",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Exceptional governance fit with TBP's institutional formation philosophy. The prospect's governance-first approach and permanent capital mandate are ideal for the Protocol Establishment Round's founding stewardship layer.",
    best_tbp_entry_point: "TBP Capital Advisory & Coordination Office",
    suggested_conversation_angle:
      "Governance dialogue — presenting TBP's Protocol Establishment Round as an institutional formation opportunity that aligns with their governance-first capital mandate and stewardship philosophy.",
    recommended_contact_route: "Swiss Family Office network, Geneva finance community, Campden Wealth events",
    likely_diligence_questions: [
      "What governance council structures are in place for the Protocol Establishment Round?",
      "What are the stewardship commitment obligations and safeguards?",
    ],
    diligence_flags: [],
    suitability_score: 90,
    scoring_breakdown: {
      familyOfficeFit: 19,
      permanentCapitalOrientation: 20,
      sectorAlignment: 17,
      governanceInstitutionalMindset: 15,
      strategicAdjacencyTBP: 12,
      engagementReadiness: 7,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Reviewed",
    assigned_owner: "Global Strategist",
    next_action: "Submit for TBP Leadership approval and prepare approach strategy",
    next_action_date: "2026-07-05",
    briefing_pack_status: "Generated",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-26T00:00:00Z",
  },

  // ── INDIA ──────────────────────────────────────────────────
  {
    id: "p-019",
    prospect_name: "India Infrastructure Family Office Group A",
    prospect_type: "family-holding-company",
    country: "India",
    city: "Mumbai",
    region: "South Asia",
    source_quality: "High",
    key_public_contacts: "Family principal named in Economic Times and SEBI filings",
    family_or_group_background:
      "Mumbai-based family holding company with significant exposure to Indian infrastructure, ports, and logistics. The family has generational wealth in trade and manufacturing and is increasingly pursuing global corridor investments.",
    investment_philosophy:
      "Long-horizon family capital with emphasis on infrastructure, logistics, and emerging corridor investments. Strong governance framework with family investment committee.",
    known_investment_themes: ["Indian infrastructure", "Port logistics", "Global corridors", "Trade"],
    sector_interests: ["Infrastructure", "Logistics", "Ports", "Trade", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Strong fit for TBP Global Nomadic Trader Ecosystem and TBP Saudi Red Sea Corridor given India-Middle East corridor interest. Port and logistics exposure aligns directly with TBP's corridor strategy.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Strategic adjacency — positioning TBP's corridor infrastructure as a neutral governance layer that connects Indian port and logistics assets with global trade corridors.",
    recommended_contact_route: "Confederation of Indian Industry (CII), Indian Chamber of Commerce, infrastructure advisory networks",
    likely_diligence_questions: ["How does TBP's corridor interact with India-Middle East trade frameworks?"],
    diligence_flags: ["Governance language not publicly evident"],
    suitability_score: 81,
    scoring_breakdown: {
      familyOfficeFit: 17,
      permanentCapitalOrientation: 18,
      sectorAlignment: 19,
      governanceInstitutionalMindset: 12,
      strategicAdjacencyTBP: 10,
      engagementReadiness: 5,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Tharushi",
    next_action: "Generate briefing pack",
    next_action_date: "2026-07-18",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-05T00:00:00Z",
    updated_at: "2026-06-24T00:00:00Z",
  },

  // ── MALAYSIA ──────────────────────────────────────────────
  {
    id: "p-020",
    prospect_name: "Malaysia Strategic Family Office Group A",
    prospect_type: "single-family-office",
    country: "Malaysia",
    city: "Kuala Lumpur",
    region: "Southeast Asia",
    source_quality: "Medium",
    key_public_contacts: "Named in Forbes Malaysia and Bursa Malaysia filings",
    family_or_group_background:
      "Kuala Lumpur-based single-family office with exposure to Malaysian plantation industries, real estate, and logistics. The founding family has increasingly diversified into technology and digital infrastructure.",
    investment_philosophy:
      "Generational stewardship capital transitioning from traditional plantation and real estate into technology, digital infrastructure, and corridor investments.",
    known_investment_themes: ["Plantation", "Real estate", "Technology", "Digital infrastructure", "Corridor investments"],
    sector_interests: ["Real Estate", "Technology", "Data Infrastructure", "Trade", "Food / Agribusiness"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: false,
    infrastructure_exposure: "Medium",
    energy_exposure: "Low",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "High",
    technology_digital_infrastructure_exposure: "High",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Secondary fit for TBP Indonesia Southeast Asia Corridor and ASMOFP™ Data Infrastructure angle. Digital transition interest is relevant. Plantation and agribusiness background may limit corridor fit.",
    best_tbp_entry_point: "ASMOFP™ Offshore Energy / Data Infrastructure",
    suggested_conversation_angle:
      "Digital infrastructure alignment — framing TBP's data corridor layer as a natural extension of their digital transition thesis.",
    recommended_contact_route: "Malaysian FO networks, Kuala Lumpur digital infrastructure forums",
    likely_diligence_questions: ["What digital infrastructure mandates does TBP support?"],
    diligence_flags: ["Direct investment activity not confirmed", "Plantation background may limit sector alignment"],
    suitability_score: 68,
    scoring_breakdown: {
      familyOfficeFit: 16,
      permanentCapitalOrientation: 16,
      sectorAlignment: 14,
      governanceInstitutionalMindset: 10,
      strategicAdjacencyTBP: 8,
      engagementReadiness: 4,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Identified",
    assigned_owner: "Tharushi",
    next_action: "Profile and score",
    next_action_date: "2026-07-25",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-08T00:00:00Z",
    updated_at: "2026-06-20T00:00:00Z",
  },

  // ── HONG KONG ─────────────────────────────────────────────
  {
    id: "p-021",
    prospect_name: "Hong Kong Trade Family Office A",
    prospect_type: "single-family-office",
    country: "Hong Kong",
    city: "Hong Kong",
    region: "East Asia",
    source_quality: "High",
    key_public_contacts: "Founding family publicly named in SCMP and HKEX filings",
    family_or_group_background:
      "Hong Kong-based single-family office with generational roots in global trade, shipping, and infrastructure. The family has operated trade and shipping businesses across Asia, the Middle East, and Europe for multiple generations.",
    investment_philosophy:
      "Multi-generational stewardship of trade and maritime assets. Long-duration capital with global corridor exposure. Strong institutional governance framework.",
    known_investment_themes: ["Global trade", "Shipping infrastructure", "Maritime", "Multi-corridor"],
    sector_interests: ["Trade", "Logistics", "Maritime", "Ports", "Infrastructure"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Top-tier multi-corridor fit. Relevant for TBP Indonesia Southeast Asia Corridor, TBP London Corridor, TBP Saudi Red Sea Corridor, and TBP Global Nomadic Trader Ecosystem. Multi-generational trade and shipping heritage is the ideal TBP stewardship profile.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Family-office stewardship layer — positioning TBP's neutral trade protocol as the institutional governance layer for their multi-generation trade and maritime heritage.",
    recommended_contact_route: "Hong Kong FO Association, HKEX advisory networks, shipping industry associations",
    likely_diligence_questions: ["How does TBP's neutral trade protocol interact with Hong Kong's existing trade infrastructure?"],
    diligence_flags: [],
    suitability_score: 91,
    scoring_breakdown: {
      familyOfficeFit: 19,
      permanentCapitalOrientation: 19,
      sectorAlignment: 20,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 13,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack",
    next_action_date: "2026-07-10",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-02T00:00:00Z",
    updated_at: "2026-06-25T00:00:00Z",
  },

  // ── CANADA ─────────────────────────────────────────────────
  {
    id: "p-022",
    prospect_name: "Canada Infrastructure Stewardship Group A",
    prospect_type: "permanent-capital-private-group",
    country: "Canada",
    city: "Toronto",
    region: "North America",
    source_quality: "Medium",
    key_public_contacts: "Managing Principal named in Globe and Mail and CVCA",
    family_or_group_background:
      "Toronto-based permanent capital group with exposure to Canadian infrastructure, energy, and global logistics. The group has a formal ESG and stewardship framework and has participated in international infrastructure co-investment.",
    investment_philosophy:
      "Permanent-capital infrastructure and energy investments with formal ESG and stewardship integration. Long-duration holds with co-investment preferred.",
    known_investment_themes: ["Canadian infrastructure", "Energy transition", "ESG stewardship", "Global co-investment"],
    sector_interests: ["Infrastructure", "Energy", "Logistics", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "Medium",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Good fit for TBP Capital Advisory & Coordination Office and ASMOFP™ Energy angle. ESG stewardship framework aligns with TBP's governance-safe institutional philosophy.",
    best_tbp_entry_point: "TBP Capital Advisory & Coordination Office",
    suggested_conversation_angle:
      "Governance dialogue — presenting TBP's Protocol Establishment Round as an ESG-aligned, governance-safe institutional formation opportunity.",
    recommended_contact_route: "CVCA (Canadian Venture Capital Association), Canadian Pension and Infrastructure forums",
    likely_diligence_questions: ["How does TBP integrate ESG considerations into corridor development?"],
    diligence_flags: ["Emerging markets exposure limited — international framing required"],
    suitability_score: 76,
    scoring_breakdown: {
      familyOfficeFit: 17,
      permanentCapitalOrientation: 18,
      sectorAlignment: 16,
      governanceInstitutionalMindset: 13,
      strategicAdjacencyTBP: 8,
      engagementReadiness: 4,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Profiled",
    assigned_owner: "Global Strategist",
    next_action: "Score and prepare entry note",
    next_action_date: "2026-07-28",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-06T00:00:00Z",
    updated_at: "2026-06-22T00:00:00Z",
  },

  // ── NIGERIA ───────────────────────────────────────────────
  {
    id: "p-023",
    prospect_name: "Nigeria Trade & Energy Family Office A",
    prospect_type: "family-holding-company",
    country: "Nigeria",
    city: "Lagos",
    region: "Africa",
    source_quality: "Medium",
    key_public_contacts: "Family principal named in Nairametrics and Businessday",
    family_or_group_background:
      "Lagos-based family holding company with significant exposure to oil and gas infrastructure, trade, and port logistics across West Africa. The founding family has deep government and regulatory relationships and a growing interest in corridor development.",
    investment_philosophy:
      "Long-horizon capital in energy and trade infrastructure with a growing interest in international corridor development and neutral trade zone concepts.",
    known_investment_themes: ["Oil and gas", "Trade infrastructure", "West Africa ports", "Corridor development"],
    sector_interests: ["Energy", "Trade", "Ports", "Logistics", "Infrastructure", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: false,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Relevant for TBP Global Nomadic Trader Ecosystem and Africa corridor strategy. Energy and trade infrastructure exposure aligns, but governance maturity needs to be assessed.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Long-duration infrastructure formation — introducing TBP's corridor concept as a governance framework for their energy and trade infrastructure ambitions across West Africa.",
    recommended_contact_route: "Lagos Chamber of Commerce, Nigerian Economic Summit Group, energy industry networks",
    likely_diligence_questions: ["What legal structure supports the Protocol Establishment Round in West Africa?"],
    diligence_flags: ["Permanent capital indicators uncertain", "Governance maturity requires verification"],
    suitability_score: 65,
    scoring_breakdown: {
      familyOfficeFit: 14,
      permanentCapitalOrientation: 13,
      sectorAlignment: 16,
      governanceInstitutionalMindset: 9,
      strategicAdjacencyTBP: 8,
      engagementReadiness: 5,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Identified",
    assigned_owner: "Global Strategist",
    next_action: "Profile and assess governance maturity",
    next_action_date: "2026-08-01",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-09T00:00:00Z",
    updated_at: "2026-06-20T00:00:00Z",
  },

  // ── KENYA ─────────────────────────────────────────────────
  {
    id: "p-024",
    prospect_name: "Kenya East Africa Trade Family Group A",
    prospect_type: "family-controlled-investment-company",
    country: "Kenya",
    city: "Nairobi",
    region: "Africa",
    source_quality: "Low",
    key_public_contacts: "Unknown — research required",
    family_or_group_background:
      "Nairobi-based family-controlled investment company with exposure to East African trade, logistics, and real estate. The founding family has interests in the East African Community and corridor development.",
    investment_philosophy: "Regional trade and logistics investment with growing institutional ambition.",
    known_investment_themes: ["East African trade", "Logistics", "Real estate", "EAC corridor"],
    sector_interests: ["Trade", "Logistics", "Real Estate", "Emerging Markets"],
    long_horizon_capital_indicators: false,
    permanent_capital_indicators: false,
    direct_investment_activity: true,
    infrastructure_exposure: "Low",
    energy_exposure: "Low",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Monitor prospect. Trade and logistics exposure is relevant for TBP's Africa strategy but institutional maturity is limited. May be revisited as the group's governance framework develops.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Introduce TBP's corridor concept at an appropriate stage of their institutional development.",
    recommended_contact_route: "Nairobi trade networks, EAC business forums",
    likely_diligence_questions: [],
    diligence_flags: ["Low governance maturity", "Limited contact intelligence", "Permanent capital not evident"],
    suitability_score: 48,
    scoring_breakdown: {
      familyOfficeFit: 11,
      permanentCapitalOrientation: 9,
      sectorAlignment: 13,
      governanceInstitutionalMindset: 7,
      strategicAdjacencyTBP: 5,
      engagementReadiness: 3,
    },
    classification: "Not Currently Suitable",
    pipeline_stage: "Identified",
    assigned_owner: "Global Strategist",
    next_action: "Monitor and revisit in 12 months",
    next_action_date: "2027-06-01",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-12T00:00:00Z",
    updated_at: "2026-06-20T00:00:00Z",
  },

  // ── BRAZIL ────────────────────────────────────────────────
  {
    id: "p-025",
    prospect_name: "Brazil Infrastructure Family Group A",
    prospect_type: "family-holding-company",
    country: "Brazil",
    city: "São Paulo",
    region: "Latin America",
    source_quality: "Medium",
    key_public_contacts: "Named in Valor Econômico and CVM filings",
    family_or_group_background:
      "São Paulo-based family holding company with exposure to Brazilian agricultural logistics, port infrastructure, and energy. The founding family has significant generational wealth in agribusiness and is expanding into infrastructure co-investment.",
    investment_philosophy:
      "Long-horizon stewardship capital in agricultural logistics, port infrastructure, and energy. Growing interest in international corridor formation.",
    known_investment_themes: ["Agribusiness logistics", "Port infrastructure", "Energy", "International corridors"],
    sector_interests: ["Food / Agribusiness", "Logistics", "Ports", "Energy", "Infrastructure"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "High",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Relevant for TBP Global Nomadic Trader Ecosystem and food/agribusiness corridor angle. Port infrastructure and agricultural logistics alignment is strong.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Permanent-capital alignment — positioning TBP's corridor formation as a neutral infrastructure layer that extends their agricultural logistics and port infrastructure exposure globally.",
    recommended_contact_route: "Brazilian Chamber of Commerce, São Paulo agribusiness and infrastructure forums",
    likely_diligence_questions: ["How does TBP's corridor relate to existing Mercosur trade frameworks?"],
    diligence_flags: ["Governance language not publicly evident"],
    suitability_score: 73,
    scoring_breakdown: {
      familyOfficeFit: 16,
      permanentCapitalOrientation: 17,
      sectorAlignment: 16,
      governanceInstitutionalMindset: 11,
      strategicAdjacencyTBP: 9,
      engagementReadiness: 4,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Profiled",
    assigned_owner: "Global Strategist",
    next_action: "Score and prepare corridor matching note",
    next_action_date: "2026-08-01",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-07T00:00:00Z",
    updated_at: "2026-06-22T00:00:00Z",
  },

  // ── MEXICO ────────────────────────────────────────────────
  {
    id: "p-026",
    prospect_name: "Mexico Industrial Family Office Group A",
    prospect_type: "single-family-office",
    country: "Mexico",
    city: "Mexico City",
    region: "Latin America",
    source_quality: "Medium",
    key_public_contacts: "Named in Expansión and BMV filings",
    family_or_group_background:
      "Mexico City-based single-family office with diversified industrial and manufacturing exposure. The founding family has generational wealth in industrial manufacturing and trade, with growing interest in North America corridor infrastructure.",
    investment_philosophy:
      "Generational stewardship capital in industrial manufacturing, trade, and North America corridor infrastructure. Strong governance orientation.",
    known_investment_themes: ["Industrial manufacturing", "North America trade", "Corridor infrastructure"],
    sector_interests: ["Manufacturing", "Trade", "Infrastructure", "Industrial Platforms", "Logistics"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "Medium",
    energy_exposure: "Medium",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "Low",
    emerging_markets_exposure: "Medium",
    governance_stewardship_language: false,
    tbp_relevance_summary:
      "Secondary fit for TBP New York/Newark North America Neutral Trade Corridor. Manufacturing and North America trade exposure creates adjacency, but governance maturity needs verification.",
    best_tbp_entry_point: "TBP New York/Newark North America Neutral Trade Corridor",
    suggested_conversation_angle:
      "Strategic adjacency — linking TBP's North America corridor governance layer to their existing manufacturing and trade infrastructure.",
    recommended_contact_route: "CANACINTRA, Mexican Business Council, AMCHAM networks",
    likely_diligence_questions: ["How does TBP's North America corridor relate to USMCA trade architecture?"],
    diligence_flags: ["Governance language not publicly evident", "Emerging market framing required"],
    suitability_score: 66,
    scoring_breakdown: {
      familyOfficeFit: 15,
      permanentCapitalOrientation: 16,
      sectorAlignment: 14,
      governanceInstitutionalMindset: 10,
      strategicAdjacencyTBP: 7,
      engagementReadiness: 4,
    },
    classification: "Strong Potential Prospect",
    pipeline_stage: "Identified",
    assigned_owner: "Global Strategist",
    next_action: "Profile prospect",
    next_action_date: "2026-08-10",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-10T00:00:00Z",
    updated_at: "2026-06-20T00:00:00Z",
  },

  // ── ADDITIONAL GULF ───────────────────────────────────────
  {
    id: "p-027",
    prospect_name: "Riyadh Strategic Family Capital Group A",
    prospect_type: "family-controlled-investment-company",
    country: "Saudi Arabia",
    city: "Riyadh",
    region: "Gulf & Middle East",
    source_quality: "High",
    key_public_contacts: "Principal named at Saudi Green Initiative and Future Investment Initiative",
    family_or_group_background:
      "Riyadh-based family-controlled investment company aligned with Saudi Vision 2030. Exposure to energy transition, financial services, and infrastructure. Active at FII Institute and international sovereign forums.",
    investment_philosophy:
      "Vision 2030-aligned long-duration capital with emphasis on energy transition, infrastructure formation, and international corridor development.",
    known_investment_themes: ["Vision 2030", "Energy transition", "Infrastructure formation", "International corridors"],
    sector_interests: ["Energy", "Infrastructure", "Financial Services", "Trade", "Technology"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "High",
    energy_exposure: "High",
    logistics_transport_exposure: "Medium",
    real_estate_exposure: "Medium",
    technology_digital_infrastructure_exposure: "High",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Priority fit for TBP Saudi Red Sea Corridor and TBP Capital Advisory & Coordination Office. Vision 2030 alignment, FII network access, and energy-infrastructure combination make this a high-priority approach target.",
    best_tbp_entry_point: "TBP Saudi Red Sea Corridor",
    suggested_conversation_angle:
      "Institutional formation round — aligning TBP's Saudi corridor with their Vision 2030 mandate and presenting stewardship as a governance-safe institutional participation framework.",
    recommended_contact_route: "FII Institute, Saudi Green Initiative, Riyadh Chamber networks",
    likely_diligence_questions: ["How does TBP's corridor align with Vision 2030 giga-projects?"],
    diligence_flags: [],
    suitability_score: 88,
    scoring_breakdown: {
      familyOfficeFit: 18,
      permanentCapitalOrientation: 18,
      sectorAlignment: 19,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 12,
      engagementReadiness: 7,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Approved for Approach",
    assigned_owner: "Global Strategist",
    next_action: "Seek introduction via FII network",
    next_action_date: "2026-07-05",
    briefing_pack_status: "Generated",
    created_at: "2026-06-01T00:00:00Z",
    updated_at: "2026-06-26T00:00:00Z",
  },
  {
    id: "p-028",
    prospect_name: "London Adviser & Introducer Channel A",
    prospect_type: "adviser-introducer-channel",
    country: "United Kingdom",
    city: "London",
    region: "United Kingdom & Europe",
    source_quality: "High",
    key_public_contacts: "Managing Partner named in Financial Times family wealth coverage",
    family_or_group_background:
      "London-based independent advisory firm specialising in family office capital introduction and institutional structuring. Has relationships with 50+ global family offices across Europe, Gulf, and Asia.",
    investment_philosophy:
      "Advisory and introduction capacity only. Facilitates institutional co-formation opportunities for family office clients.",
    known_investment_themes: ["Capital introduction", "Family office advisory", "Institutional structuring"],
    sector_interests: ["Financial Services", "Trade", "Infrastructure"],
    long_horizon_capital_indicators: false,
    permanent_capital_indicators: false,
    direct_investment_activity: false,
    infrastructure_exposure: "None",
    energy_exposure: "None",
    logistics_transport_exposure: "None",
    real_estate_exposure: "None",
    technology_digital_infrastructure_exposure: "None",
    emerging_markets_exposure: "Medium",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Warm introduction channel rather than direct prospect. Can facilitate access to 50+ family offices across Europe, Gulf, and Asia. Governance-safe advisory relationship.",
    best_tbp_entry_point: "TBP Capital Advisory & Coordination Office",
    suggested_conversation_angle:
      "Position TBP's Capital Advisory Office as a strategic partner for their family office clients seeking long-duration institutional formation opportunities.",
    recommended_contact_route: "Direct professional introduction via family office conference",
    likely_diligence_questions: ["What is TBP's fee arrangement with advisers?", "Is TBP regulated in the UK?"],
    diligence_flags: ["Adviser/introducer channel — not a direct investment prospect"],
    suitability_score: 55,
    scoring_breakdown: {
      familyOfficeFit: 8,
      permanentCapitalOrientation: 5,
      sectorAlignment: 10,
      governanceInstitutionalMindset: 14,
      strategicAdjacencyTBP: 12,
      engagementReadiness: 6,
    },
    classification: "Monitor / Secondary Prospect",
    pipeline_stage: "Identified",
    assigned_owner: "Global Strategist",
    next_action: "Engage as introducer channel rather than direct prospect",
    next_action_date: "2026-07-20",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-08T00:00:00Z",
    updated_at: "2026-06-22T00:00:00Z",
  },
  {
    id: "p-029",
    prospect_name: "Singapore Private Bank Family Office Desk A",
    prospect_type: "private-bank-family-office-desk",
    country: "Singapore",
    city: "Singapore",
    region: "Southeast Asia",
    source_quality: "Medium",
    key_public_contacts: "Head of Family Office Solutions named in Asian Private Banker",
    family_or_group_background:
      "Singapore-based private bank family office desk with access to 30+ ultra-high net worth Asian family office mandates. Strong relationships across Southeast Asia, South Asia, and the Gulf.",
    investment_philosophy:
      "Facilitates family office co-investment in institutional-grade infrastructure and alternative capital formations.",
    known_investment_themes: ["Family office co-investment", "Infrastructure alternatives", "Asian capital"],
    sector_interests: ["Infrastructure", "Financial Services", "Trade", "Emerging Markets"],
    long_horizon_capital_indicators: false,
    permanent_capital_indicators: false,
    direct_investment_activity: false,
    infrastructure_exposure: "None",
    energy_exposure: "None",
    logistics_transport_exposure: "None",
    real_estate_exposure: "None",
    technology_digital_infrastructure_exposure: "None",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Warm channel to Asian family office mandates. Not a direct investment prospect but can facilitate access to multiple UHNW family offices across the region.",
    best_tbp_entry_point: "TBP Capital Advisory & Coordination Office",
    suggested_conversation_angle:
      "Introduce TBP's Protocol Establishment Round as an institutional formation opportunity appropriate for their family office mandate clients.",
    recommended_contact_route: "Asian Private Banker networks, Singapore FO ecosystem",
    likely_diligence_questions: ["What regulatory approval is needed for private bank distribution?"],
    diligence_flags: ["Channel prospect — individual FO mandates need separate profiling"],
    suitability_score: 58,
    scoring_breakdown: {
      familyOfficeFit: 9,
      permanentCapitalOrientation: 6,
      sectorAlignment: 11,
      governanceInstitutionalMindset: 13,
      strategicAdjacencyTBP: 12,
      engagementReadiness: 7,
    },
    classification: "Monitor / Secondary Prospect",
    pipeline_stage: "Identified",
    assigned_owner: "Tharushi",
    next_action: "Engage as channel and obtain mandate list for profiling",
    next_action_date: "2026-07-20",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-09T00:00:00Z",
    updated_at: "2026-06-22T00:00:00Z",
  },
  {
    id: "p-030",
    prospect_name: "Switzerland Zurich Trade Holding Group B",
    prospect_type: "family-holding-company",
    country: "Switzerland",
    city: "Zurich",
    region: "United Kingdom & Europe",
    source_quality: "High",
    key_public_contacts: "Family principal named in NZZ and Swiss FO Association",
    family_or_group_background:
      "Zurich-based family holding company with generational exposure to global trade, commodities, and financial services. The family has operated trade and commodity businesses connecting Europe, the Middle East, and Asia for three generations.",
    investment_philosophy:
      "Multi-generational permanent capital in global trade, commodities, and financial services. Governance-first philosophy with family advisory council.",
    known_investment_themes: ["Global trade", "Commodities", "Financial services", "Multi-corridor trade"],
    sector_interests: ["Trade", "Financial Services", "Logistics", "Emerging Markets"],
    long_horizon_capital_indicators: true,
    permanent_capital_indicators: true,
    direct_investment_activity: true,
    infrastructure_exposure: "Medium",
    energy_exposure: "Medium",
    logistics_transport_exposure: "High",
    real_estate_exposure: "Low",
    technology_digital_infrastructure_exposure: "Medium",
    emerging_markets_exposure: "High",
    governance_stewardship_language: true,
    tbp_relevance_summary:
      "Strong multi-corridor fit. Relevant for TBP Global Nomadic Trader Ecosystem and TBP London Canary Wharf Corridor. Multi-generational trade heritage and governance-first philosophy are excellent TBP alignment signals.",
    best_tbp_entry_point: "TBP Global Nomadic Trader Ecosystem",
    suggested_conversation_angle:
      "Family-office stewardship layer — positioning TBP's neutral trade protocol as the institutional governance layer for their multi-generational, multi-corridor trade exposure.",
    recommended_contact_route: "Swiss FO Association, Zurich trade community, commodity trading networks",
    likely_diligence_questions: ["What Swiss legal structures are compatible with TBP's governance framework?"],
    diligence_flags: [],
    suitability_score: 85,
    scoring_breakdown: {
      familyOfficeFit: 18,
      permanentCapitalOrientation: 18,
      sectorAlignment: 17,
      governanceInstitutionalMindset: 15,
      strategicAdjacencyTBP: 11,
      engagementReadiness: 6,
    },
    classification: "Priority Founding Steward Prospect",
    pipeline_stage: "Scored",
    assigned_owner: "Global Strategist",
    next_action: "Generate briefing pack",
    next_action_date: "2026-07-12",
    briefing_pack_status: "Not Generated",
    created_at: "2026-06-03T00:00:00Z",
    updated_at: "2026-06-24T00:00:00Z",
  },
];

export function getKPISummary() {
  const total = mockProspects.length;
  const profiled = mockProspects.filter(
    (p) => p.pipeline_stage !== "Identified"
  ).length;
  const scored = mockProspects.filter(
    (p) =>
      p.pipeline_stage !== "Identified" && p.pipeline_stage !== "Profiled"
  ).length;
  const priority = mockProspects.filter(
    (p) => p.classification === "Priority Founding Steward Prospect"
  ).length;
  const strong = mockProspects.filter(
    (p) => p.classification === "Strong Potential Prospect"
  ).length;
  const diligence = mockProspects.filter(
    (p) =>
      p.pipeline_stage === "Diligence / Review" ||
      p.diligence_flags.length > 1
  ).length;
  const packs = mockProspects.filter(
    (p) => p.briefing_pack_status === "Generated" || p.briefing_pack_status === "Approved" || p.briefing_pack_status === "Sent"
  ).length;
  const meetings = mockProspects.filter(
    (p) =>
      p.pipeline_stage === "Meeting Proposed" ||
      p.pipeline_stage === "Meeting Scheduled"
  ).length;
  const joined = mockProspects.filter(
    (p) => p.pipeline_stage === "Joined Circle"
  ).length;

  return {
    totalProspects: total,
    profiled,
    scored,
    priorityFoundingSteward: priority,
    strongPotential: strong,
    requiresDiligenceReview: diligence,
    briefingPacksGenerated: packs,
    meetingOpportunities: meetings,
    foundingStewardsSecured: joined,
    targetFoundingStewards: 20,
  };
}
