import type { Task } from "@/types";

export const mockTasks: Task[] = [
  {
    id: "task-001",
    title: "Build Indonesia family office longlist",
    description: "Research and document at least 15 Indonesian family offices and investment groups using publicly available sources. Include profile fields, sector interests, and public source references.",
    assignedTo: "Tharushi",
    status: "Done",
    priority: "High",
    dueDate: "2026-06-25",
    linkedProspects: ["p-007", "p-008"],
    tags: ["Indonesia", "Longlist", "Research"],
  },
  {
    id: "task-002",
    title: "Build Singapore family office gateway map",
    description: "Map Singapore family office ecosystem including SFOs, MFOs, private bank FO desks, and adviser channels. Include at least 10 profiles with sector interests and engagement pathways.",
    assignedTo: "Tharushi",
    status: "Done",
    priority: "High",
    dueDate: "2026-06-25",
    linkedProspects: ["p-005", "p-006", "p-029"],
    tags: ["Singapore", "Mapping", "Research"],
  },
  {
    id: "task-003",
    title: "Build Sri Lanka family office map",
    description: "Research Sri Lankan family offices and investment groups. Focus on Colombo-based entities with port infrastructure and trade exposure.",
    assignedTo: "Tharushi",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2026-07-10",
    linkedProspects: ["p-009"],
    tags: ["Sri Lanka", "Mapping", "Research"],
  },
  {
    id: "task-004",
    title: "Build Central Asia prospect map",
    description: "Research family offices and investment groups in Kazakhstan, Uzbekistan, and wider Central Asia. Focus on energy, logistics, and corridor-adjacent capital.",
    assignedTo: "Global Strategist",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-07-15",
    linkedProspects: ["p-010", "p-011"],
    tags: ["Central Asia", "Kazakhstan", "Uzbekistan", "Research"],
  },
  {
    id: "task-005",
    title: "Score top 10 Indonesia prospects",
    description: "Apply TBP suitability scoring model to the 10 best Indonesia prospects. Document scoring breakdown and classification for each. Flag any data gaps.",
    assignedTo: "Tharushi",
    status: "Done",
    priority: "High",
    dueDate: "2026-06-25",
    linkedProspects: ["p-007", "p-008"],
    tags: ["Indonesia", "Scoring", "Priority"],
  },
  {
    id: "task-006",
    title: "Generate five briefing packs for priority prospects",
    description: "Generate internal briefing packs for the top 5 Priority Founding Steward prospects. Each pack must include all 11 sections and pass the Governance Language Check before submission.",
    assignedTo: "Tharushi",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-07-10",
    linkedProspects: ["p-005", "p-012", "p-018", "p-003", "p-021"],
    tags: ["Briefing Packs", "Priority", "Content"],
  },
  {
    id: "task-007",
    title: "Review governance language on all draft outreach",
    description: "Pass all draft outreach emails, briefing note introductions, and follow-up templates through the TBP Governance Language Checker. Document results and obtain TBP Leadership sign-off.",
    assignedTo: "Tharushi",
    status: "Todo",
    priority: "High",
    dueDate: "2026-07-12",
    linkedProspects: [],
    tags: ["Governance", "Compliance", "Review"],
  },
  {
    id: "task-008",
    title: "Prepare corridor matching notes for Gulf prospects",
    description: "Complete corridor matching analysis for all Gulf & Middle East prospects (Jeddah, Dubai, Abu Dhabi, Doha, Riyadh). Submit corridor matching matrix to Capital Advisory Lead.",
    assignedTo: "Global Strategist",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-07-08",
    linkedProspects: ["p-012", "p-013", "p-014", "p-015", "p-027"],
    tags: ["Gulf", "Corridor Matching", "Analysis"],
  },
  {
    id: "task-009",
    title: "Update prospect pipeline for all active prospects",
    description: "Review and update pipeline stage for all 30 prospects in the system. Ensure next actions and next action dates are current. Flag any prospects that have gone stale.",
    assignedTo: "Tharushi",
    status: "Todo",
    priority: "Medium",
    dueDate: "2026-07-05",
    linkedProspects: [],
    tags: ["Pipeline", "CRM", "Maintenance"],
  },
  {
    id: "task-010",
    title: "Prepare AI engine recommendation note",
    description: "Draft the TBP Family Office Circle Intelligence & Coordination Engine recommendation note. Include data fields, scoring model, automation opportunities, governance safeguards, and CRM workflow design.",
    assignedTo: "Tharushi",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2026-07-20",
    linkedProspects: [],
    tags: ["AI Engine", "Recommendation", "Strategic"],
  },
  {
    id: "task-011",
    title: "Research warm introduction pathways for top 5 prospects",
    description: "Identify specific warm introduction pathways for the 5 highest-scoring prospects. Focus on shared networks, conferences, and adviser channels. Document in prospect profiles.",
    assignedTo: "Global Strategist",
    status: "Todo",
    priority: "High",
    dueDate: "2026-07-15",
    linkedProspects: ["p-012", "p-005", "p-003", "p-018", "p-021"],
    tags: ["Introductions", "Networking", "Pipeline"],
  },
  {
    id: "task-012",
    title: "Complete London prospect research phase",
    description: "Research and document at least 10 London and UK-based family office prospects. Prioritise those with trade, maritime, logistics, and infrastructure exposure.",
    assignedTo: "Global Strategist",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2026-07-25",
    linkedProspects: ["p-003", "p-004", "p-028"],
    tags: ["London", "UK", "Research"],
  },
  {
    id: "task-013",
    title: "Prepare Gulf outreach strategy note",
    description: "Draft a strategy note for engaging the Gulf prospects. Include timing, conference opportunities, and FII network approach strategy. Submit for Ribi Jayasinghe review.",
    assignedTo: "Global Strategist",
    status: "Review",
    priority: "High",
    dueDate: "2026-07-05",
    linkedProspects: ["p-012", "p-027"],
    tags: ["Gulf", "Strategy", "Outreach"],
  },
  {
    id: "task-014",
    title: "Set up Supabase database and connect to dashboard",
    description: "Configure Supabase project, run schema SQL, seed with mock prospect data, and connect to Next.js dashboard via API routes.",
    assignedTo: "Tharushi",
    status: "Todo",
    priority: "Medium",
    dueDate: "2026-07-30",
    linkedProspects: [],
    tags: ["Technical", "Database", "Infrastructure"],
  },
  {
    id: "task-015",
    title: "Finalise scored shortlist for Leadership review",
    description: "Compile the top 10 scored prospects into a formal shortlist document. Include scoring breakdown, classification, and recommended next steps for each. Submit to Ribi Jayasinghe.",
    assignedTo: "Tharushi",
    status: "Todo",
    priority: "High",
    dueDate: "2026-07-08",
    linkedProspects: ["p-005", "p-012", "p-003", "p-018", "p-021", "p-014", "p-001", "p-013", "p-010", "p-027"],
    tags: ["Shortlist", "Review", "Priority"],
  },
];
